app = "recipes-api"
primary_region = "sin"  # Singapore region (gần Việt Nam)
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "3333"
  HOST = "0.0.0.0"
  NODE_ENV = "production"

[[services]]
  internal_port = 3333
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    timeout = "2s"
