app = "recipes-api"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "3333"
  HOST = "0.0.0.0"
  NODE_ENV = "production"
  DB_CONNECTION = "sqlite"
  SQLITE_DB_NAME = "/app/tmp/database.sqlite"

[[services]]
  internal_port = 3333
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    timeout = "2s"

[mounts]
  source = "data"
  destination = "/app/tmp"


