app = "recipes-api"
primary_region = "sin"

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "3333"
  HOST = "0.0.0.0"
  NODE_ENV = "production"

[[services]]
  internal_port = 3333
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
[mounts]
  source = "app_database"
  destination = "/app/database"